
file_service:
  type: "local"  # options: "local" or "s3"
  basedir:

logging:
  format: "%(name)s - %(asctime)s - %(levelname)s - %(message)s"

resources:
  brands: resources/seeds/brands.csv
#  brands: resources/seeds/brands_tiny.csv

webdriver:
  chrome_binary_path:
  chromedriver_path:
  chrome_options:
    - "--disable-blink-features=AutomationControlled"
    - "--blink-settings=imagesEnabled=false"
    - "--disable-search-engine-choice-screen"
    - "--headless=new"
    - "--disable-dev-shm-usage"
    - "--no-sandbox"
  use_stealth: true
  timeout_seconds: 30

database:
  url: "sqlite:///data/db/carscout.db"
  echo: false

http:
  url: "https://olx.ba/kategorije"
  client_type: "requests"  # options: "requests" or "httpx"
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
    Accept-Encoding: "gzip, deflate, br, zstd"
    Accept: "application/json, text/plain, */*"
    referer: "https://olx.ba/kategorije"

scrapers:
  listing_scraper:
    min_req_delay: 1 # minimum delay before a request is made (in seconds)
    max_req_delay: 4 # maximum delay before a request is made (in seconds)
    timeout: 20 # how long to wait for a response (in seconds)
    created_gte: "-7+days" # minimum age of the listing (api query parameter)
  vehicle_scraper:
    min_req_delay: 1 # minimum delay before a request is made (in seconds)
    max_req_delay: 4 # maximum delay before a request is made (in seconds)
    timeout: 20 # how long to wait for a response (in seconds)
    reinit_session_every: 500
