
file_service:
  type: "local"  # options: "local" or "s3"
  basedir:

logging:
  # log_level: 20 # INFO
  log_level: 10 # DEBUG
  format: "%(name)s - %(asctime)s - %(levelname)s - %(message)s"

redis:
  url: "redis://localhost:6379/0"

resources:
  brands: resources/seeds/brands_tiny.csv

db:
  # todo: will be reconfigured
  url: "sqlite:///data/carscout_251204.db"
  echo: false

webdriver:
  chrome_binary_path: ""  # path to chrome/chromium binary (will try auto-detect if left empty)
  chromedriver_path: ""  # path to ChromeDriver executable (will try auto-detect if left empty)
  chrome_options:
    - "--disable-blink-features=AutomationControlled"
    - "--blink-settings=imagesEnabled=false"
    - "--disable-search-engine-choice-screen"
    - "--headless=new"
    - "--disable-dev-shm-usage"
    - "--no-sandbox"
  use_stealth: true
  timeout_seconds: 30

http:
  url: "https://olx.ba/kategorije"
  client_type: "requests"  # options: "requests" or "httpx"
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
    Accept-Encoding: "gzip, deflate, br, zstd"
    Accept: "application/json, text/plain, */*"
    referer: "https://olx.ba/kategorije"

scrapers:
  listing_scraper:
    min_req_delay: 1 # minimum delay before a request is made (in seconds)
    max_req_delay: 3 # maximum delay before a request is made (in seconds)
    timeout: 10 # how long to wait for a response (in seconds)
  vehicle_scraper:
    min_req_delay: 1 # minimum delay before a request is made (in seconds)
    max_req_delay: 3 # maximum delay before a request is made (in seconds)
    timeout: 10 # how long to wait for a response (in seconds)
    reinit_session_every: 500
