api:
  base_url: "https://olx.ba/api"
  category_id: "18"
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

db:
  host: 
  database: vsa
  collections:
    vehicles: "vehicles"

paths:
  base_path: "data"
  brands_and_models_prefix: "brands_and_models"
  listings_prefix: "listings"
  vehicles_prefix: "vehicles"

selenium:
  chrome_options:
    - --disable-search-engine-choice-screen
    - --headless=new
    - --no-sandbox
    - --disable-dev-shm-usage
    - --disable-gpu
